# This CI will lauch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 

name: CI with install

on:
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'CITATION.cff'
      - 'LICENSE.txt'
      - 'readthedocs.yml'

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install package
        run: |
          python setup.py install --user

      - name: install packages needed for testing
        run: |
          pip install -r requirements-test.txt

      - name: Run tests
        run: |
          pytest tests -v --cov=lithium_enrichment_cost_calculator --cov-append --cov-report term --cov-report xml

      - name: test examples
        run: |
          python examples/examples_from_readme.py
          python examples/find_cost_of_enrichment.py
          python examples/find_minimal_cost_of_enrichment.py

      - name: Upload to codecov
        uses: codecov/codecov-action@v2
